package geneticAlgorithm.utils;

import geneticAlgorithm.Individual;
import random.RandomGenerator;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/**
 * Utility class with some methods.
 */
public class Utils {

    /**
     * Normalizes an array to 0-1 interval.
     * @param numberArray The array to be normalized
     * @return The normalized array.
     */
    public static double[] normalizeDoubleArray(double[] numberArray){
        double divisor = 0;
        for (double number: numberArray) {
            divisor += number;
        }

        int arrayLength = numberArray.length;
        double[] normalizedArray = new double[arrayLength];

        if (divisor!=0) {

            for (int i = 0; i < arrayLength; i++) {
                normalizedArray[i] = numberArray[i] / divisor;
            }
        }
        return normalizedArray;


    }

    /**
     *
     * @param popSize Size of the population to be generated.
     * @param individualPrime First individual, from which the others will be generated by shuffling.
     * @return A population of individuals of size {@code popSize} and cromosomes based
     * on the one of {@code individualPrime}
     */
    public static List<Individual> generatePopulationOfSizeFromIndividual(int popSize, Individual individualPrime) {
        List<Individual> population = new ArrayList<>();
        population.add(individualPrime);
        Random gn = RandomGenerator.getGeneratorWithSeed(10);
        List<Integer> cromosomePrime = individualPrime.getChromosome();
        for (int i = 0; i < popSize-1; i++) {
            List<Integer> cromosomeClone = new ArrayList<>(cromosomePrime);
            Collections.shuffle(cromosomeClone, gn);
            population.add(new Individual(cromosomeClone));
        }
        return population;
    }
}
